-- Insert sample properties
INSERT INTO properties (
  id,
  owner_id,
  name,
  description,
  address,
  city,
  state,
  zip_code,
  status,
  daily_rate,
  weekly_rate,
  monthly_rate,
  images,
  created_at,
  updated_at
) VALUES
(
  'prop_1',
  'user_1',
  'Modern Studio in Downtown',
  'A beautifully furnished studio apartment in the heart of downtown. Perfect for short or long stays.',
  '123 Main St',
  'San Francisco',
  'CA',
  '94105',
  'available',
  150,
  900,
  3000,
  ARRAY['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267'],
  NOW(),
  NOW()
),
(
  'prop_2',
  'user_1',
  'Luxury 2BR with City View',
  'Spacious 2-bedroom apartment with stunning city views. High-end amenities and modern furnishings.',
  '456 Market St',
  'San Francisco',
  'CA',
  '94103',
  'available',
  250,
  1500,
  5000,
  ARRAY['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688'],
  NOW(),
  NOW()
),
(
  'prop_3',
  'user_2',
  'Cozy 1BR near Tech Hub',
  'Comfortable 1-bedroom apartment located in the tech district. Fast internet and workspace included.',
  '789 Howard St',
  'San Francisco',
  'CA',
  '94107',
  'available',
  180,
  1100,
  3600,
  ARRAY['https://images.unsplash.com/photo-1493809842364-78817add7ffb'],
  NOW(),
  NOW()
); 